type JsonObject = Record<string, unknown>;

type Env = { KLAVIYO_PRIVATE_API_KEY?: string; KLAVIYO_OPERATIONS_API_KEY?: string };
type Claims = { iss?:string; aud?:string|string[]; sub?:string; repository?:string; repository_owner?:string; ref?:string; event_name?:string; exp?:number; iat?:number; nbf?:number };
const PATH="/internal/ops/kway-klaviyo-execute2-2026-08-11";
const API="https://a.klaviyo.com";
const REVISION="2026-07-15";
const SHOP="https://devidlabel.com";
const REPO="devidlabel/devidlabel-ai-assistant-backend";
const REF="refs/heads/ops/execute-kway-klaviyo-2026-08-11";
const SUB=`repo:${REPO}:ref:${REF}`;
const ISS="https://token.actions.githubusercontent.com";
const AUD="devidlabel-kway-klaviyo-2026-08-11";
const SOURCE_CAMPAIGN="01KYW3S1ZE1CZSS8NH3GWHP464";
const PLANS=[
 {key:"aug11",name:"DL | 2026-08-11 18:30 | K-WAY | FINAL PRICE DROP | HIGH INTENT",audience:"VwRxZn",excluded:["RJwTs7","VGjrR5","XwbNZt"],subject:"K-Way: i ribassi finali sono online 🔥",preview:"Prezzi ribassati, disponibilità limitata. Se stavi aspettando, questo è il momento.",datetime:"2026-08-11T16:30:00+00:00",heading:"K-WAY / FINAL PRICE DROP",intro:"Abbiamo abbassato ancora i prezzi su una selezione K-Way. Giacche, gilet, zaini e accessori sono entrati nella fase finale dei saldi: le disponibilità che vedi online sono quelle reali.",cta:"SCOPRI K-WAY",closing:"Il prezzo è sceso. Ora è la disponibilità a decidere.",template:"DL | K-WAY FINAL PRICE DROP | 2026-08-11"},
 {key:"aug13",name:"DL | 2026-08-13 18:30 | K-WAY | PRIVATE FINAL SALE | PAST BUYERS",audience:"TzLCbS",excluded:["RJwTs7","VGjrR5","VwRxZn","XwbNZt"],subject:"K-Way, adesso conviene davvero.",preview:"La selezione è ancora più interessante. Ma taglie e colori stanno diminuendo.",datetime:"2026-08-13T16:30:00+00:00",heading:"K-WAY / RIBASSI FINALI",intro:"Ci sono momenti in cui aspettare ha senso. E momenti in cui il prezzo è arrivato esattamente dove volevi. La selezione K-Way è entrata nella fase finale dei ribassi: capispalla iconici e accessori a prezzi decisamente più interessanti.",cta:"VEDI I RIBASSI K-WAY",closing:"Niente countdown. Solo un dato concreto: quando una taglia o un colore finiscono, potrebbero non tornare.",template:"DL | K-WAY PRIVATE FINAL SALE | 2026-08-13"}
] as const;
function obj(v:unknown):JsonObject{return v&&typeof v==="object"&&!Array.isArray(v)?v as JsonObject:{}}
function s(v:unknown):string{return typeof v==="string"?v.trim():""}
function response(v:JsonObject,status=200){return new Response(JSON.stringify(v),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function b64(v:string){const n=v.replace(/-/g,"+").replace(/_/g,"/");const p=n.padEnd(Math.ceil(n.length/4)*4,"=");const bin=atob(p),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function dec<T>(v:string):T{return JSON.parse(new TextDecoder().decode(b64(v))) as T}
async function auth(r:Request){const h=r.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return false;const token=h.slice(7).trim(),parts=token.split(".");if(parts.length!==3)return false;try{const hd=dec<{alg?:string;kid?:string}>(parts[0]),c=dec<Claims>(parts[1]);if(hd.alg!=="RS256"||!hd.kid)return false;const now=Math.floor(Date.now()/1000),aud=Array.isArray(c.aud)?c.aud.includes(AUD):c.aud===AUD;if(c.iss!==ISS||!aud||c.repository!==REPO||c.repository_owner!=="devidlabel"||c.ref!==REF||c.sub!==SUB||c.event_name!=="push"||typeof c.exp!=="number"||c.exp<now-30||c.exp>now+900||typeof c.iat!=="number"||c.iat>now+30||c.iat<now-900||(typeof c.nbf==="number"&&c.nbf>now+30))return false;const cr=await fetch(`${ISS}/.well-known/openid-configuration`);if(!cr.ok)return false;const cfg=await cr.json() as {jwks_uri?:string};if(!cfg.jwks_uri)return false;const jr=await fetch(cfg.jwks_uri);if(!jr.ok)return false;const jwks=await jr.json() as {keys?:Array<JsonWebKey&{kid?:string}>};const jwk=(jwks.keys||[]).find(k=>k.kid===hd.kid);if(!jwk)return false;const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);return crypto.subtle.verify({name:"RSASSA-PKCS1-v1_5"},key,Uint8Array.from(b64(parts[2])).buffer,Uint8Array.from(new TextEncoder().encode(`${parts[0]}.${parts[1]}`)).buffer)}catch{return false}}
async function k(key:string,path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{Accept:"application/vnd.api+json",Authorization:`Klaviyo-API-Key ${key}`,revision:REVISION,...(init.body?{"Content-Type":"application/vnd.api+json"}:{}),...(init.headers||{})}});let body:JsonObject={};try{body=await r.json() as JsonObject}catch{}return{ok:r.ok,status:r.status,body}}
async function must(key:string,path:string,init:RequestInit={}){const r=await k(key,path,init);if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?obj(r.body.errors[0]):{};throw new Error(`${r.status}:${s(e.code)||s(e.title)||"Klaviyo error"}`)}return r.body}
function rid(row:JsonObject,name:string){const rel=obj(obj(row.relationships)[name]),d=rel.data;if(Array.isArray(d)&&d.length)return s(obj(d[0]).id);return s(obj(d).id)}
async function sourceMessage(key:string){const m=await must(key,`/api/campaigns/${SOURCE_CAMPAIGN}/campaign-messages?page[size]=10`);const d=Array.isArray(m.data)?m.data:[];if(!d.length)throw new Error("source campaign message missing");return s(obj(d[0]).id)}
async function sender(key:string){const id=await sourceMessage(key);const d=await must(key,`/api/campaign-messages/${id}`);const a=obj(obj(d.data).attributes),def=obj(a.definition),content=obj(def.content);const from_email=s(content.from_email),from_label=s(content.from_label),reply_to_email=s(content.reply_to_email)||from_email;if(!from_email||!from_label||!reply_to_email)throw new Error("historical sender missing");return{from_email,from_label,reply_to_email,source_message_id:id}}
async function fallbackTemplate(key:string){const id=await sourceMessage(key);const d=await must(key,`/api/campaign-messages/${id}?include=template`);const rel=rid(obj(d.data),"template");if(rel)return rel;for(const x of Array.isArray(d.included)?d.included:[]){const o=obj(x);if(s(o.type)==="template"&&s(o.id))return s(o.id)}throw new Error("fallback template missing")}
async function image(handle:string){try{const r=await fetch(`${SHOP}/products/${handle}.js`,{headers:{Accept:"application/json"}});if(!r.ok)return"";const p=await r.json() as JsonObject;const f=s(p.featured_image);if(f)return f.startsWith("//")?`https:${f}`:f;return""}catch{return""}}
async function productImages(){return Promise.all(["k-way-giacca-jack-stretch-nylon-jersey-blue-insignia-kwayk3123uwb67","k-way-giacca-marguerite-stretch-poly-jersey-violet-glicine-kwayk8138pwh41","k-way-zaino-laon-black-pure-kwayk2116rwusy","k-way-pochette-nimes-black-pure-kwayk4127swusy"].map(image))}
function esc(v:string){return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function html(p:(typeof PLANS)[number],imgs:string[]){const valid=imgs.filter(Boolean);const cards=valid.map((src,i)=>`<td width="50%" style="padding:6px"><a href="${SHOP}/collections/k-way" style="text-decoration:none"><img src="${esc(src)}" width="270" style="display:block;width:100%;height:auto;background:#f2f2f2" alt="K-Way"><div style="font:700 12px Arial;color:#111;letter-spacing:1.4px;padding:10px 3px">${["GIACCHE","CAPISPALLA","ZAINI","ACCESSORI"][i]} →</div></a></td>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:620px){.w{width:100%!important}.h{font-size:38px!important;line-height:40px!important}.p{padding-left:22px!important;padding-right:22px!important}.g td{display:block!important;width:100%!important}}</style></head><body style="margin:0;background:#ececec"><table width="100%" role="presentation"><tr><td align="center"><table class="w" width="600" role="presentation" style="width:600px;max-width:600px;background:#fff"><tr><td align="center" style="background:#080808;padding:27px"><a href="${SHOP}" style="font:900 22px Arial;color:#fff;text-decoration:none;letter-spacing:5px">DEVID LABEL</a></td></tr><tr><td class="p" style="padding:45px 44px 12px"><span style="background:#d71920;color:#fff;font:900 12px Arial;letter-spacing:1.7px;padding:8px 12px">FINAL SALE</span><div class="h" style="font:900 48px/49px Arial;color:#080808;letter-spacing:-2px;margin-top:21px">${esc(p.heading)}</div><div style="width:72px;height:5px;background:#d71920;margin:24px 0"></div><p style="font:17px/27px Arial;color:#262626;margin:0">${esc(p.intro)}</p></td></tr><tr><td class="p" style="padding:22px 44px 38px"><a href="${SHOP}/collections/k-way" style="display:inline-block;background:#080808;color:#fff;text-decoration:none;font:900 13px Arial;letter-spacing:1.5px;padding:17px 24px">${esc(p.cta)}</a></td></tr>${cards?`<tr><td style="padding:0 18px 30px"><table class="g" width="100%" role="presentation"><tr>${cards}</tr></table></td></tr>`:""}<tr><td class="p" style="background:#f3f3f3;padding:31px 44px"><p style="font:800 20px/28px Arial;color:#111;margin:0">${esc(p.closing)}</p></td></tr><tr><td align="center" style="padding:28px;font:11px/18px Arial;color:#777">Devid Label · M.A.R.E. Srl<br><a href="${SHOP}/collections/k-way" style="color:#111">K-Way su Devid Label</a> · {% unsubscribe %}</td></tr></table></td></tr></table></body></html>`}
async function createTemplate(keys:string[],name:string,markup:string){for(const [i,key] of keys.entries()){const r=await k(key,"/api/templates",{method:"POST",body:JSON.stringify({data:{type:"template",attributes:{name,editor_type:"CODE",html:markup}}})});if(r.ok)return{id:s(obj(r.body.data).id),source:i===0?"private_key":"operations_key"};if(![401,403].includes(r.status))throw new Error(`template ${r.status}`)}return null}
async function findCampaign(key:string,name:string){const filter=encodeURIComponent(`and(equals(messages.channel,'email'),contains(name,'${name.replace(/'/g,"\\'")}'))`);const d=await must(key,`/api/campaigns?filter=${filter}&include=campaign-messages&page[size]=10`);for(const x of Array.isArray(d.data)?d.data:[]){const o=obj(x);if(s(obj(o.attributes).name)===name)return o}return null}
async function campaignMessage(key:string,id:string,row:JsonObject){const rel=rid(row,"campaign-messages");if(rel)return rel;const d=await must(key,`/api/campaigns/${id}/campaign-messages?page[size]=10`);const a=Array.isArray(d.data)?d.data:[];return a.length?s(obj(a[0]).id):""}
async function createCampaign(key:string,p:(typeof PLANS)[number],snd:{from_email:string;from_label:string;reply_to_email:string}){const found=await findCampaign(key,p.name);if(found)return found;const payload={data:{type:"campaign",attributes:{name:p.name,audiences:{included:[p.audience],excluded:[...p.excluded]},send_strategy:{method:"static",datetime:p.datetime,options:{is_local:false}},send_options:{use_smart_sending:true},tracking_options:{add_tracking_params:true,custom_tracking_params:[],is_tracking_clicks:true,is_tracking_opens:true},"campaign-messages":{data:[{type:"campaign-message",attributes:{definition:{channel:"email",label:p.name,content:{subject:p.subject,preview_text:p.preview,from_email:snd.from_email,from_label:snd.from_label,reply_to_email:snd.reply_to_email}}}}]}}}};return obj((await must(key,"/api/campaigns",{method:"POST",body:JSON.stringify(payload)})).data)}
async function assign(key:string,msg:string,template:string){await must(key,"/api/campaign-message-assign-template",{method:"POST",body:JSON.stringify({data:{type:"campaign-message",id:msg,relationships:{template:{data:{type:"template",id:template}}}}})})}
async function schedule(key:string,id:string){const r=await k(key,"/api/campaign-send-jobs",{method:"POST",body:JSON.stringify({data:{type:"campaign-send-job",id}})});if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?obj(r.body.errors[0]):{};throw new Error(`schedule ${r.status} ${s(e.code)||s(e.title)}`)}return obj(r.body.data)}
async function status(key:string,id:string){const d=await must(key,`/api/campaigns/${id}?include=campaign-messages`),row=obj(d.data),a=obj(row.attributes);return{id:s(row.id),name:s(a.name),status:s(a.status),send_strategy:a.send_strategy??null,audiences:a.audiences??null,send_options:a.send_options??null}}
async function execute(env:Env){const op=s(env.KLAVIYO_OPERATIONS_API_KEY),priv=s(env.KLAVIYO_PRIVATE_API_KEY);if(!op)return{ok:false,operation:"kway_klaviyo_execute2",error:"operations key missing"};const snd=await sender(op),imgs=await productImages(),keys=[priv,op].filter(Boolean),results:JsonObject[]=[];let fallback="";for(const p of PLANS){try{let t=await createTemplate(keys,p.template,html(p,imgs));if(!t){fallback=fallback||await fallbackTemplate(op);t={id:fallback,source:"existing_kway_template"}}const row=await createCampaign(op,p,snd);const id=s(row.id),msg=await campaignMessage(op,id,row);if(!id||!msg)throw new Error("campaign/message id missing");await assign(op,msg,t.id);const before=await status(op,id);let job:JsonObject={};if(s(before.status).toLowerCase()==="draft")job=await schedule(op,id);const after=await status(op,id);results.push({ok:true,key:p.key,campaign_id:id,campaign_message_id:msg,template_id:t.id,template_source:t.source,target_rome:p.key==="aug11"?"2026-08-11 18:30":"2026-08-13 18:30",included:[p.audience],excluded:[...p.excluded],smart_sending:true,send_job_status:s(obj(job.attributes).status)||null,status:after.status,send_strategy:after.send_strategy})}catch(e){results.push({ok:false,key:p.key,error:e instanceof Error?e.message.slice(0,220):"unknown"})}}return{ok:results.every(x=>x.ok===true),operation:"kway_klaviyo_execute2",generated_at:new Date().toISOString(),sender_source_campaign:SOURCE_CAMPAIGN,sender:{from_email:snd.from_email,from_label:snd.from_label,reply_to_email:snd.reply_to_email},product_images_found:imgs.filter(Boolean).length,results}}
async function read(env:Env){const op=s(env.KLAVIYO_OPERATIONS_API_KEY);if(!op)return{ok:false,operation:"kway_klaviyo_status2"};const rows=[];for(const p of PLANS){const c=await findCampaign(op,p.name);rows.push(c?await status(op,s(c.id)):{name:p.name,status:"not_found"})}return{ok:true,operation:"kway_klaviyo_status2",campaigns:rows}}
export async function handleKwayKlaviyoExecute2Once(request:Request,env:Env):Promise<Response|null>{if(new URL(request.url).pathname!==PATH)return null;if(!(await auth(request)))return response({ok:false,operation:"kway_klaviyo_execute2",reason:"not_found"},404);if(request.method==="POST")try{return response(await execute(env))}catch(e){return response({ok:false,operation:"kway_klaviyo_execute2",error:e instanceof Error?e.message:"failed"},500)}if(request.method==="GET")try{return response(await read(env))}catch(e){return response({ok:false,operation:"kway_klaviyo_status2",error:e instanceof Error?e.message:"failed"},500)}return response({ok:false,reason:"method_not_allowed"},405)}
