type J = Record<string, unknown>;
type Env = { KLAVIYO_PRIVATE_API_KEY?: string; KLAVIYO_OPERATIONS_API_KEY?: string };
type Claims = { iss?:string; aud?:string|string[]; sub?:string; repository?:string; repository_owner?:string; ref?:string; event_name?:string; exp?:number; iat?:number; nbf?:number };

const PATH="/internal/ops/kway-klaviyo-execute3-2026-08-11";
const API="https://a.klaviyo.com";
const REV="2026-07-15";
const SHOP="https://devidlabel.com";
const SOURCE="01KYW3S1ZE1CZSS8NH3GWHP464";
const REPO="devidlabel/devidlabel-ai-assistant-backend";
const REF="refs/heads/ops/execute-kway-klaviyo-2026-08-11";
const ISS="https://token.actions.githubusercontent.com";
const AUD="devidlabel-kway-klaviyo-2026-08-11";
const SUB=`repo:${REPO}:ref:${REF}`;

const PLANS=[
 {key:"aug11",name:"DL | 2026-08-11 18:30 | K-WAY | FINAL PRICE DROP | HIGH INTENT",inc:"VwRxZn",exc:["RJwTs7","VGjrR5","XwbNZt"],subject:"K-Way: i ribassi finali sono online 🔥",preview:"Prezzi ribassati, disponibilità limitata. Se stavi aspettando, questo è il momento.",when:"2026-08-11T16:30:00+00:00",heading:"K-WAY / FINAL PRICE DROP",intro:"Abbiamo abbassato ancora i prezzi su una selezione K-Way. Giacche, gilet, zaini e accessori sono entrati nella fase finale dei saldi: le disponibilità che vedi online sono quelle reali.",cta:"SCOPRI K-WAY",closing:"Il prezzo è sceso. Ora è la disponibilità a decidere.",template:"DL | K-WAY FINAL PRICE DROP | 2026-08-11"},
 {key:"aug13",name:"DL | 2026-08-13 18:30 | K-WAY | PRIVATE FINAL SALE | PAST BUYERS",inc:"TzLCbS",exc:["RJwTs7","VGjrR5","VwRxZn","XwbNZt"],subject:"K-Way, adesso conviene davvero.",preview:"La selezione è ancora più interessante. Ma taglie e colori stanno diminuendo.",when:"2026-08-13T16:30:00+00:00",heading:"K-WAY / RIBASSI FINALI",intro:"Ci sono momenti in cui aspettare ha senso. E momenti in cui il prezzo è arrivato esattamente dove volevi. La selezione K-Way è entrata nella fase finale dei ribassi: capispalla iconici e accessori a prezzi decisamente più interessanti.",cta:"VEDI I RIBASSI K-WAY",closing:"Niente countdown. Solo un dato concreto: quando una taglia o un colore finiscono, potrebbero non tornare.",template:"DL | K-WAY PRIVATE FINAL SALE | 2026-08-13"}
] as const;

const o=(v:unknown):J=>v&&typeof v==="object"&&!Array.isArray(v)?v as J:{};
const s=(v:unknown):string=>typeof v==="string"?v.trim():"";
const res=(v:J,status=200)=>new Response(JSON.stringify(v),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
function b64(v:string){const n=v.replace(/-/g,"+").replace(/_/g,"/");const p=n.padEnd(Math.ceil(n.length/4)*4,"=");const b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function dec<T>(v:string):T{return JSON.parse(new TextDecoder().decode(b64(v))) as T}
async function auth(r:Request){const h=r.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return false;const t=h.slice(7).trim(),p=t.split(".");if(p.length!==3)return false;try{const hd=dec<{alg?:string;kid?:string}>(p[0]),c=dec<Claims>(p[1]);if(hd.alg!=="RS256"||!hd.kid)return false;const now=Math.floor(Date.now()/1000),aud=Array.isArray(c.aud)?c.aud.includes(AUD):c.aud===AUD;if(c.iss!==ISS||!aud||c.repository!==REPO||c.repository_owner!=="devidlabel"||c.ref!==REF||c.sub!==SUB||c.event_name!=="push"||typeof c.exp!=="number"||c.exp<now-30||c.exp>now+900||typeof c.iat!=="number"||c.iat>now+30||c.iat<now-900||(typeof c.nbf==="number"&&c.nbf>now+30))return false;const cr=await fetch(`${ISS}/.well-known/openid-configuration`);if(!cr.ok)return false;const cfg=await cr.json() as {jwks_uri?:string};if(!cfg.jwks_uri)return false;const jr=await fetch(cfg.jwks_uri);if(!jr.ok)return false;const jwks=await jr.json() as {keys?:Array<JsonWebKey&{kid?:string}>};const jwk=(jwks.keys||[]).find(k=>k.kid===hd.kid);if(!jwk)return false;const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);return crypto.subtle.verify({name:"RSASSA-PKCS1-v1_5"},key,Uint8Array.from(b64(p[2])).buffer,Uint8Array.from(new TextEncoder().encode(`${p[0]}.${p[1]}`)).buffer)}catch{return false}}

async function k(key:string,path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{Accept:"application/vnd.api+json",Authorization:`Klaviyo-API-Key ${key}`,revision:REV,...(init.body?{"Content-Type":"application/vnd.api+json"}:{}),...(init.headers||{})}});let body:J={};try{body=await r.json() as J}catch{}return{ok:r.ok,status:r.status,body}}
async function must(key:string,path:string,init:RequestInit={}){const r=await k(key,path,init);if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?o(r.body.errors[0]):{};throw new Error(`${path} :: ${r.status} :: ${s(e.code)||s(e.title)||s(e.detail)||"Klaviyo error"}`)}return r.body}
function relId(row:J,name:string){const rel=o(o(row.relationships)[name]),d=rel.data;if(Array.isArray(d)&&d.length)return s(o(d[0]).id);return s(o(d).id)}
function campaignMessageFromPayload(body:J){const data=o(body.data);let id=relId(data,"campaign-messages");if(id)return id;for(const x of Array.isArray(body.included)?body.included:[]){const q=o(x);if(s(q.type)==="campaign-message"&&s(q.id))return s(q.id)}return""}
async function getCampaignBundle(key:string,id:string){return must(key,`/api/campaigns/${id}?include=campaign-messages`)}
async function source(key:string){const bundle=await getCampaignBundle(key,SOURCE);const msgId=campaignMessageFromPayload(bundle);if(!msgId)throw new Error("source campaign message id missing");const d=await must(key,`/api/campaign-messages/${msgId}`);const a=o(o(d.data).attributes),content=o(o(a.definition).content);const from_email=s(content.from_email),from_label=s(content.from_label),reply_to_email=s(content.reply_to_email)||from_email;if(!from_email||!from_label||!reply_to_email)throw new Error("source sender fields missing");return{msgId,from_email,from_label,reply_to_email}}
async function sourceTemplate(key:string,msgId:string){const d=await must(key,`/api/campaign-messages/${msgId}?include=template`);let id=relId(o(d.data),"template");if(id)return id;for(const x of Array.isArray(d.included)?d.included:[]){const q=o(x);if(s(q.type)==="template"&&s(q.id))return s(q.id)}throw new Error("source template missing")}

async function productImage(handle:string){try{const r=await fetch(`${SHOP}/products/${handle}.js`,{headers:{Accept:"application/json"}});if(!r.ok)return"";const p=await r.json() as J;const f=s(p.featured_image);return f?(f.startsWith("//")?`https:${f}`:f):""}catch{return""}}
async function images(){return Promise.all(["k-way-giacca-jack-stretch-nylon-jersey-blue-insignia-kwayk3123uwb67","k-way-giacca-marguerite-stretch-poly-jersey-violet-glicine-kwayk8138pwh41","k-way-zaino-laon-black-pure-kwayk2116rwusy","k-way-pochette-nimes-black-pure-kwayk4127swusy"].map(productImage))}
const esc=(v:string)=>v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function html(p:(typeof PLANS)[number],imgs:string[]){const cards=imgs.filter(Boolean).map((src,i)=>`<td width="50%" style="padding:6px;vertical-align:top"><a href="${SHOP}/collections/k-way" style="text-decoration:none"><img src="${esc(src)}" width="270" style="display:block;width:100%;height:auto;background:#f1f1f1" alt="K-Way"><div style="font:700 12px Arial;color:#111;letter-spacing:1.4px;padding:10px 3px">${["GIACCHE","CAPISPALLA","ZAINI","ACCESSORI"][i]} →</div></a></td>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:620px){.w{width:100%!important}.h{font-size:38px!important;line-height:40px!important}.p{padding-left:22px!important;padding-right:22px!important}.g td{display:block!important;width:100%!important}}</style></head><body style="margin:0;background:#ececec"><table width="100%" role="presentation"><tr><td align="center"><table class="w" width="600" role="presentation" style="width:600px;max-width:600px;background:#fff"><tr><td align="center" style="background:#080808;padding:27px"><a href="${SHOP}" style="font:900 22px Arial;color:#fff;text-decoration:none;letter-spacing:5px">DEVID LABEL</a></td></tr><tr><td class="p" style="padding:45px 44px 12px"><span style="background:#d71920;color:#fff;font:900 12px Arial;letter-spacing:1.7px;padding:8px 12px">FINAL SALE</span><div class="h" style="font:900 48px/49px Arial;color:#080808;letter-spacing:-2px;margin-top:21px">${esc(p.heading)}</div><div style="width:72px;height:5px;background:#d71920;margin:24px 0"></div><p style="font:17px/27px Arial;color:#262626;margin:0">${esc(p.intro)}</p></td></tr><tr><td class="p" style="padding:22px 44px 38px"><a href="${SHOP}/collections/k-way" style="display:inline-block;background:#080808;color:#fff;text-decoration:none;font:900 13px Arial;letter-spacing:1.5px;padding:17px 24px">${esc(p.cta)}</a></td></tr>${cards?`<tr><td style="padding:0 18px 30px"><table class="g" width="100%" role="presentation"><tr>${cards}</tr></table></td></tr>`:""}<tr><td class="p" style="background:#f3f3f3;padding:31px 44px"><p style="font:800 20px/28px Arial;color:#111;margin:0">${esc(p.closing)}</p></td></tr><tr><td align="center" style="padding:28px;font:11px/18px Arial;color:#777">Devid Label · M.A.R.E. Srl<br><a href="${SHOP}/collections/k-way" style="color:#111">K-Way su Devid Label</a> · {% unsubscribe %}</td></tr></table></td></tr></table></body></html>`}
async function createTemplate(keys:string[],name:string,markup:string){for(const [i,key] of keys.entries()){if(!key)continue;const r=await k(key,"/api/templates",{method:"POST",body:JSON.stringify({data:{type:"template",attributes:{name,editor_type:"CODE",html:markup}}})});if(r.ok)return{id:s(o(r.body.data).id),source:i===0?"private_key":"operations_key"};if(![401,403].includes(r.status)){const e=Array.isArray(r.body.errors)&&r.body.errors.length?o(r.body.errors[0]):{};throw new Error(`/api/templates :: ${r.status} :: ${s(e.code)||s(e.title)||s(e.detail)||"invalid"}`)}}return null}

function filterLiteral(v:string){return v.replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
async function findCampaign(key:string,name:string){const q=new URLSearchParams();q.set("filter",`and(equals(messages.channel,'email'),contains(name,'${filterLiteral(name)}'))`);q.set("fields[campaign]","id,name,status,send_strategy,audiences,send_options");q.set("include","campaign-messages");q.set("page[size]","10");const d=await must(key,"/api/campaigns?"+q.toString());for(const x of Array.isArray(d.data)?d.data:[]){const row=o(x);if(s(o(row.attributes).name)===name)return row}return null}
async function createCampaign(key:string,p:(typeof PLANS)[number],snd:{from_email:string;from_label:string;reply_to_email:string}){const existing=await findCampaign(key,p.name);if(existing)return existing;const body={data:{type:"campaign",attributes:{name:p.name,audiences:{included:[p.inc],excluded:[...p.exc]},send_strategy:{method:"static",datetime:p.when,options:{is_local:false}},send_options:{use_smart_sending:true},tracking_options:{add_tracking_params:true,custom_tracking_params:[],is_tracking_clicks:true,is_tracking_opens:true},"campaign-messages":{data:[{type:"campaign-message",attributes:{definition:{channel:"email",label:p.name,content:{subject:p.subject,preview_text:p.preview,from_email:snd.from_email,from_label:snd.from_label,reply_to_email:snd.reply_to_email}}}}]}}}};return o((await must(key,"/api/campaigns",{method:"POST",body:JSON.stringify(body)})).data)}
async function messageId(key:string,campaign:J){let id=relId(campaign,"campaign-messages");if(id)return id;const cid=s(campaign.id);if(!cid)return"";return campaignMessageFromPayload(await getCampaignBundle(key,cid))}
async function assign(key:string,msg:string,template:string){await must(key,"/api/campaign-message-assign-template",{method:"POST",body:JSON.stringify({data:{type:"campaign-message",id:msg,relationships:{template:{data:{type:"template",id:template}}}}})})}
async function status(key:string,id:string){const d=await getCampaignBundle(key,id),row=o(d.data),a=o(row.attributes);return{id:s(row.id),name:s(a.name),status:s(a.status),send_strategy:a.send_strategy??null,audiences:a.audiences??null,send_options:a.send_options??null}}
async function schedule(key:string,id:string){const r=await k(key,"/api/campaign-send-jobs",{method:"POST",body:JSON.stringify({data:{type:"campaign-send-job",id}})});if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?o(r.body.errors[0]):{};throw new Error(`/api/campaign-send-jobs :: ${r.status} :: ${s(e.code)||s(e.title)||s(e.detail)||"invalid"}`)}return o(r.body.data)}
async function finalStatus(key:string,id:string){for(let i=0;i<6;i++){const x=await status(key,id);if(["Scheduled","Sent"].includes(s(x.status)))return x;await new Promise(r=>setTimeout(r,700))}return status(key,id)}

async function execute(env:Env){const op=s(env.KLAVIYO_OPERATIONS_API_KEY),priv=s(env.KLAVIYO_PRIVATE_API_KEY);if(!op)return{ok:false,operation:"kway_klaviyo_execute3",error:"operations key missing"};const src=await source(op),imgs=await images(),keys=[priv,op].filter(Boolean),fallback=await sourceTemplate(op,src.msgId),results:J[]=[];for(const p of PLANS){try{let t=await createTemplate(keys,p.template,html(p,imgs));if(!t)t={id:fallback,source:"existing_kway_template"};const campaign=await createCampaign(op,p,src);const id=s(campaign.id),msg=await messageId(op,campaign);if(!id||!msg)throw new Error("campaign/message id missing");const before=await status(op,id);if(s(before.status).toLowerCase()==="draft"){await assign(op,msg,t.id);await schedule(op,id)}const after=await finalStatus(op,id);results.push({ok:["Scheduled","Sent"].includes(s(after.status)),key:p.key,campaign_id:id,campaign_message_id:msg,template_id:t.id,template_source:t.source,status:after.status,target_rome:p.key==="aug11"?"2026-08-11 18:30":"2026-08-13 18:30",included:[p.inc],excluded:[...p.exc],smart_sending:true,send_strategy:after.send_strategy})}catch(e){results.push({ok:false,key:p.key,error:e instanceof Error?e.message.slice(0,350):"unknown"})}}return{ok:results.every(x=>x.ok===true),operation:"kway_klaviyo_execute3",generated_at:new Date().toISOString(),sender_source_campaign:SOURCE,product_images_found:imgs.filter(Boolean).length,results}}
async function read(env:Env){const op=s(env.KLAVIYO_OPERATIONS_API_KEY);if(!op)return{ok:false,operation:"kway_klaviyo_status3"};const rows:J[]=[];for(const p of PLANS){const c=await findCampaign(op,p.name);rows.push(c?await status(op,s(c.id)):{name:p.name,status:"not_found"})}return{ok:true,operation:"kway_klaviyo_status3",campaigns:rows}}

export async function handleKwayKlaviyoExecute3Once(request:Request,env:Env):Promise<Response|null>{if(new URL(request.url).pathname!==PATH)return null;if(!(await auth(request)))return res({ok:false,operation:"kway_klaviyo_execute3",reason:"not_found"},404);if(request.method==="POST")try{return res(await execute(env))}catch(e){return res({ok:false,operation:"kway_klaviyo_execute3",error:e instanceof Error?e.message:"failed"},500)}if(request.method==="GET")try{return res(await read(env))}catch(e){return res({ok:false,operation:"kway_klaviyo_status3",error:e instanceof Error?e.message:"failed"},500)}return res({ok:false,reason:"method_not_allowed"},405)}
