type J = Record<string, unknown>;
type Env = { KLAVIYO_OPERATIONS_API_KEY?: string };
type Claims = { iss?:string; aud?:string|string[]; sub?:string; repository?:string; repository_owner?:string; ref?:string; event_name?:string; exp?:number; iat?:number; nbf?:number };
const PATH="/internal/ops/kway-klaviyo-aug13-2026-08-11";
const API="https://a.klaviyo.com";
const REV="2026-07-15";
const SHOP="https://devidlabel.com";
const SOURCE="01KYW3S1ZE1CZSS8NH3GWHP464";
const REPO="devidlabel/devidlabel-ai-assistant-backend";
const REF="refs/heads/ops/execute-kway-klaviyo-2026-08-11";
const ISS="https://token.actions.githubusercontent.com";
const AUD="devidlabel-kway-klaviyo-2026-08-11";
const SUB=`repo:${REPO}:ref:${REF}`;
const NAME="DL | 2026-08-13 18:30 | K-WAY | PRIVATE FINAL SALE | HISTORICAL K-WAY";
const CANDIDATES=["Wqtagj","XXKUUu","Ry6mRM"] as const;
const EXCLUDED=["RJwTs7","VGjrR5","VwRxZn","XwbNZt"];
const SUBJECT="K-Way, adesso conviene davvero.";
const PREVIEW="La selezione è ancora più interessante. Ma taglie e colori stanno diminuendo.";
const WHEN="2026-08-13T16:30:00+00:00";
const TEMPLATE_NAME="DL | K-WAY PRIVATE FINAL SALE | 2026-08-13";
const o=(v:unknown):J=>v&&typeof v==="object"&&!Array.isArray(v)?v as J:{};
const s=(v:unknown):string=>typeof v==="string"?v.trim():"";
const res=(v:J,status=200)=>new Response(JSON.stringify(v),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
function b64(v:string){const n=v.replace(/-/g,"+").replace(/_/g,"/");const p=n.padEnd(Math.ceil(n.length/4)*4,"=");const b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function dec<T>(v:string):T{return JSON.parse(new TextDecoder().decode(b64(v))) as T}
async function auth(r:Request){const h=r.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return false;const t=h.slice(7).trim(),p=t.split(".");if(p.length!==3)return false;try{const hd=dec<{alg?:string;kid?:string}>(p[0]),c=dec<Claims>(p[1]);if(hd.alg!=="RS256"||!hd.kid)return false;const now=Math.floor(Date.now()/1000),aud=Array.isArray(c.aud)?c.aud.includes(AUD):c.aud===AUD;if(c.iss!==ISS||!aud||c.repository!==REPO||c.repository_owner!=="devidlabel"||c.ref!==REF||c.sub!==SUB||c.event_name!=="push"||typeof c.exp!=="number"||c.exp<now-30||c.exp>now+900||typeof c.iat!=="number"||c.iat>now+30||c.iat<now-900||(typeof c.nbf==="number"&&c.nbf>now+30))return false;const cr=await fetch(`${ISS}/.well-known/openid-configuration`);if(!cr.ok)return false;const cfg=await cr.json() as {jwks_uri?:string};if(!cfg.jwks_uri)return false;const jr=await fetch(cfg.jwks_uri);if(!jr.ok)return false;const jwks=await jr.json() as {keys?:Array<JsonWebKey&{kid?:string}>};const jwk=(jwks.keys||[]).find(k=>k.kid===hd.kid);if(!jwk)return false;const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);return crypto.subtle.verify({name:"RSASSA-PKCS1-v1_5"},key,Uint8Array.from(b64(p[2])).buffer,Uint8Array.from(new TextEncoder().encode(`${p[0]}.${p[1]}`)).buffer)}catch{return false}}
async function k(key:string,path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{Accept:"application/vnd.api+json",Authorization:`Klaviyo-API-Key ${key}`,revision:REV,...(init.body?{"Content-Type":"application/vnd.api+json"}:{}),...(init.headers||{})}});let body:J={};try{body=await r.json() as J}catch{}return{ok:r.ok,status:r.status,body}}
async function must(key:string,path:string,init:RequestInit={}){const r=await k(key,path,init);if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?o(r.body.errors[0]):{};throw new Error(`${path} :: ${r.status} :: ${s(e.code)||s(e.title)||s(e.detail)||"Klaviyo error"}`)}return r.body}
function relId(row:J,name:string){const d=o(o(row.relationships)[name]).data;if(Array.isArray(d)&&d.length)return s(o(d[0]).id);return s(o(d).id)}
function msgFrom(body:J){let id=relId(o(body.data),"campaign-messages");if(id)return id;for(const x of Array.isArray(body.included)?body.included:[]){const q=o(x);if(s(q.type)==="campaign-message"&&s(q.id))return s(q.id)}return""}
async function source(key:string){const b=await must(key,`/api/campaigns/${SOURCE}?include=campaign-messages`),msg=msgFrom(b);if(!msg)throw new Error("source message missing");const d=await must(key,`/api/campaign-messages/${msg}`),a=o(o(d.data).attributes),c=o(o(a.definition).content);const from_email=s(c.from_email),from_label=s(c.from_label),reply_to_email=s(c.reply_to_email)||from_email;if(!from_email||!from_label||!reply_to_email)throw new Error("source sender missing");return{from_email,from_label,reply_to_email}}
function html(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:620px){.w{width:100%!important}.h{font-size:38px!important;line-height:40px!important}.p{padding-left:22px!important;padding-right:22px!important}.tile{display:block!important;width:auto!important;margin:8px 0!important}}</style></head><body style="margin:0;background:#ededed"><table width="100%" role="presentation"><tr><td align="center"><table class="w" width="600" role="presentation" style="width:600px;max-width:600px;background:#fff"><tr><td align="center" style="background:#080808;padding:27px"><a href="${SHOP}" style="font:900 22px Arial;color:#fff;text-decoration:none;letter-spacing:5px">DEVID LABEL</a></td></tr><tr><td class="p" style="padding:48px 44px 20px"><span style="background:#d71920;color:#fff;font:900 12px Arial;letter-spacing:1.8px;padding:8px 12px">RIBASSI FINALI</span><div class="h" style="font:900 48px/49px Arial;color:#080808;letter-spacing:-2px;margin:22px 0">K-WAY<br>PRIVATE FINAL SALE</div><div style="width:72px;height:5px;background:#d71920;margin:0 0 25px"></div><p style="font:17px/27px Arial;color:#262626;margin:0">Ci sono momenti in cui aspettare ha senso. E momenti in cui il prezzo è arrivato esattamente dove volevi. La selezione K-Way è entrata nella fase finale dei ribassi: capispalla iconici e accessori a prezzi decisamente più interessanti.</p></td></tr><tr><td class="p" style="padding:8px 44px 30px"><a href="${SHOP}/collections/k-way" style="display:inline-block;background:#080808;color:#fff;text-decoration:none;font:900 13px Arial;letter-spacing:1.5px;padding:17px 24px">VEDI I RIBASSI K-WAY</a></td></tr><tr><td class="p" style="padding:0 44px 38px"><table width="100%" role="presentation"><tr><td class="tile" style="background:#f3f3f3;padding:21px;font:900 17px Arial;letter-spacing:1px">GIACCHE →</td><td width="10"></td><td class="tile" style="background:#f3f3f3;padding:21px;font:900 17px Arial;letter-spacing:1px">ZAINI →</td></tr><tr><td height="10"></td></tr><tr><td class="tile" style="background:#f3f3f3;padding:21px;font:900 17px Arial;letter-spacing:1px">ACCESSORI →</td><td width="10"></td><td class="tile" style="background:#d71920;color:#fff;padding:21px;font:900 17px Arial;letter-spacing:1px">FINAL SALE →</td></tr></table></td></tr><tr><td class="p" style="background:#080808;padding:32px 44px"><p style="font:800 20px/29px Arial;color:#fff;margin:0">Niente countdown. Solo un dato concreto: quando una taglia o un colore finiscono, potrebbero non tornare.</p></td></tr><tr><td align="center" style="padding:28px;font:11px/18px Arial;color:#777">Devid Label · M.A.R.E. Srl<br><a href="${SHOP}/collections/k-way" style="color:#111">K-Way su Devid Label</a> · {% unsubscribe %}</td></tr></table></td></tr></table></body></html>`}
async function template(key:string){const r=await k(key,"/api/templates",{method:"POST",body:JSON.stringify({data:{type:"template",attributes:{name:TEMPLATE_NAME,editor_type:"CODE",html:html()}}})});if(!r.ok){const e=Array.isArray(r.body.errors)&&r.body.errors.length?o(r.body.errors[0]):{};throw new Error(`template :: ${r.status} :: ${s(e.code)||s(e.title)||s(e.detail)||"invalid"}`)}return s(o(r.body.data).id)}
async function create(key:string,audience:string,snd:{from_email:string;from_label:string;reply_to_email:string}){const body={data:{type:"campaign",attributes:{name:NAME,audiences:{included:[audience],excluded:EXCLUDED},send_strategy:{method:"static",datetime:WHEN,options:{is_local:false}},send_options:{use_smart_sending:true},tracking_options:{add_tracking_params:true,custom_tracking_params:[],is_tracking_clicks:true,is_tracking_opens:true},"campaign-messages":{data:[{type:"campaign-message",attributes:{definition:{channel:"email",label:NAME,content:{subject:SUBJECT,preview_text:PREVIEW,from_email:snd.from_email,from_label:snd.from_label,reply_to_email:snd.reply_to_email}}}}]}}}};const r=await k(key,"/api/campaigns",{method:"POST",body:JSON.stringify(body)});if(!r.ok)return{ok:false,status:r.status,body:r.body};return{ok:true,status:r.status,body:r.body}}
async function assign(key:string,msg:string,t:string){await must(key,"/api/campaign-message-assign-template",{method:"POST",body:JSON.stringify({data:{type:"campaign-message",id:msg,relationships:{template:{data:{type:"template",id:t}}}}})})}
async function estimation(key:string,id:string){await must(key,"/api/campaign-recipient-estimation-jobs",{method:"POST",body:JSON.stringify({data:{type:"campaign-recipient-estimation-job",id}})});for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,900));const job=await must(key,`/api/campaign-recipient-estimation-jobs/${id}`),st=s(o(o(job.data).attributes).status);if(st==="complete")break;if(st==="cancelled")return 0}const d=await must(key,`/api/campaign-recipient-estimations/${id}`);return Number(o(o(d.data).attributes).estimated_recipient_count||0)}
async function del(key:string,id:string){const r=await k(key,`/api/campaigns/${id}`,{method:"DELETE"});return r.ok||r.status===404}
async function schedule(key:string,id:string){await must(key,"/api/campaign-send-jobs",{method:"POST",body:JSON.stringify({data:{type:"campaign-send-job",id}})})}
async function status(key:string,id:string){const d=await must(key,`/api/campaigns/${id}`),a=o(o(d.data).attributes);return{id:s(o(d.data).id),name:s(a.name),status:s(a.status),audiences:a.audiences??null,send_strategy:a.send_strategy??null,send_options:a.send_options??null}}
async function find(key:string){const q=new URLSearchParams();q.set("filter",`and(equals(messages.channel,'email'),contains(name,'${NAME.replace(/'/g,"\\'")}'))`);q.set("page[size]","10");const d=await must(key,"/api/campaigns?"+q.toString());for(const x of Array.isArray(d.data)?d.data:[]){const q=o(x);if(s(o(q.attributes).name)===NAME)return q}return null}
async function execute(env:Env){const key=s(env.KLAVIYO_OPERATIONS_API_KEY);if(!key)return{ok:false,operation:"kway_aug13_execute",error:"operations key missing"};const existing=await find(key);if(existing){const st=await status(key,s(existing.id));return{ok:["Scheduled","Sent","Queued without Recipients","Preparing to schedule"].includes(s(st.status)),operation:"kway_aug13_execute",idempotent:true,campaign:st}}const snd=await source(key),t=await template(key),attempts:J[]=[];for(const audience of CANDIDATES){const c=await create(key,audience,snd);if(!c.ok){const e=Array.isArray(c.body.errors)&&c.body.errors.length?o(c.body.errors[0]):{};attempts.push({audience,created:false,status:c.status,error:s(e.code)||s(e.title)||s(e.detail)||"invalid"});continue}const campaign=o(c.body.data),id=s(campaign.id),msg=relId(campaign,"campaign-messages");if(!id||!msg)throw new Error("campaign/message id missing");let count=0;try{count=await estimation(key,id)}catch(e){attempts.push({audience,created:true,campaign_id:id,estimation_error:e instanceof Error?e.message:"failed"});await del(key,id);continue}if(count<=0){attempts.push({audience,created:true,campaign_id:id,estimated_recipients:count,discarded:true});await del(key,id);continue}await assign(key,msg,t);await schedule(key,id);await new Promise(r=>setTimeout(r,2500));const st=await status(key,id);return{ok:true,operation:"kway_aug13_execute",campaign_id:id,campaign_message_id:msg,template_id:t,audience,estimated_recipients:count,excluded:EXCLUDED,smart_sending:true,target_rome:"2026-08-13 18:30",campaign:st,attempts}}return{ok:false,operation:"kway_aug13_execute",error:"no_viable_kway_audience",attempts}}
async function read(env:Env){const key=s(env.KLAVIYO_OPERATIONS_API_KEY);if(!key)return{ok:false,operation:"kway_aug13_status"};const c=await find(key);return{ok:true,operation:"kway_aug13_status",campaign:c?await status(key,s(c.id)):{name:NAME,status:"not_found"}}}
export async function handleKwayAug13Once(request:Request,env:Env):Promise<Response|null>{if(new URL(request.url).pathname!==PATH)return null;if(!(await auth(request)))return res({ok:false,operation:"kway_aug13",reason:"not_found"},404);if(request.method==="POST")try{return res(await execute(env))}catch(e){return res({ok:false,operation:"kway_aug13_execute",error:e instanceof Error?e.message:"failed"},500)}if(request.method==="GET")try{return res(await read(env))}catch(e){return res({ok:false,operation:"kway_aug13_status",error:e instanceof Error?e.message:"failed"},500)}return res({ok:false,reason:"method_not_allowed"},405)}
